version: '3.9'

services:
  app:
    build:
      context: .
    container_name: turbo_app
    command: ["node", "apps/api/dist/main.js"]
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=Development