version: '3.9'

services:
  app:
    build:
      context: .
    container_name: turbo_app
    command: ["/bin/sh", "-c", "npm run prisma:migrate --workspace api && npm run prisma:seed --workspace api && npm run start:prod --workspace api"]
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=Development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/minicommerce?schema=public
    env_file:
      - ./apps/api/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - commerce_network
  
  postgres:
    container_name: postgres
    image: postgres:16rc1
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=minicommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "minicommerce"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
    networks:
      - commerce_network

networks:
  commerce_network: {}