export const products = [
  {
    name: 'T-Shirt',
    description: 'Majestic Mountain Graphic',
    stock: 10,
    price: 10000,
    imageUrl: 'https://i.imgur.com/QkIa5tT.jpeg',
  },
  {
    name: 'Hoodie',
    description: 'Classic Red Pullover',
    stock: 22,
    price: 14000,
    imageUrl: 'https://i.imgur.com/1twoaDy.jpeg',
  },
  {
    name: 'Hoodie',
    description: 'Classic Heather Gray',
    stock: 17,
    price: 30000,
    imageUrl: 'https://i.imgur.com/cHddUCu.jpeg',
  },
  {
    name: 'Sweatshirt',
    description: 'Classic Grey Hooded',
    stock: 10,
    price: 34000,
    imageUrl: 'https://i.imgur.com/R2PN9Wq.jpeg',
  },
  {
    name: 'Joggers',
    description: 'Classic Comfort Fit Joggers',
    stock: 35,
    price: 40000,
    imageUrl: 'https://i.imgur.com/ZKGofuB.jpeg',
  },
  {
    name: 'Joggers 2',
    description: 'Classic Comfort Drawstring',
    stock: 2,
    price: 50000,
    imageUrl: 'https://i.imgur.com/mp3rUty.jpeg',
  },
  {
    name: 'Sweatpants',
    description: 'Classic Red Jogger',
    stock: 1,
    price: 55000,
    imageUrl: 'https://i.imgur.com/9LFjwpI.jpeg',
  },
  {
    name: 'Cap',
    description: 'Classic Navy Blue Baseball',
    stock: 15,
    price: 15000,
    imageUrl: 'https://i.imgur.com/R3iobJA.jpeg',
  },
  {
    name: 'Gorra 1',
    description: 'Classic Blue Baseball Cap',
    stock: 30,
    price: 23700,
    imageUrl: 'https://i.imgur.com/wXuQ7bm.jpeg',
  },
  {
    name: 'Gorra 2',
    description: 'Classic Red Baseball Cap',
    stock: 5,
    price: 120000,
    imageUrl: 'https://i.imgur.com/cBuLvBi.jpeg',
  },
];
